baseURL = 'https://francisfu.com/'
title = 'CRuffians'
theme = 'FixIt'
languageCode = 'zh-CN'
languageName = "简体中文"
defaultContentLanguage = 'zh-cn'
hasCJKLanguage = true
[markup]
  _merge = "shallow"
[outputs]
  _merge = "shallow"
[taxonomies]
  _merge = "shallow"

[markup.goldmark]

[markup.goldmark.extensions]

[markup.goldmark.extensions.passthrough]
enable = true

[markup.goldmark.extensions.passthrough.delimiters]
block = [
  [
    '\[',
    '\]'
  ],
  [
    '$$',
    '$$'
  ]
]
inline = [
  [
    '\(',
    '\)'
  ],
  [
    '$',
    '$'
  ]
]

[menu]
  [[menu.main]]
    weight = 1
    identifier = "posts"
    # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
    pre = ""
    # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
    post = ""
    name = "文章"
    url = "/posts/"
    # 当你将鼠标悬停在此菜单链接上时, 将显示的标题
    title = ""
  [[menu.main]]
    weight = 2
    identifier = "categories"
    pre = ""
    post = ""
    name = "分类"
    url = "/categories/"
    title = ""

[params]
  description = "The Less You Know, The Further You Go."
  externalIcon = true
  images = ["icon.png"]
  [params.author]
    name = "Francis Fu"
    email = "mail@francisfu.com"
    link = "https://francisfu.com/"
    avatar = "/images/icon.png"
  [params.cookieconsent]
    enable = false
  [params.home]
    [params.home.profile]
      enable = true
      avatarURL = "/images/icon.png"
      title = "CRuffians"
      subtitle = "The Less You Know, The Further You Go."
      typeit = false
      social = true
  [params.social]
    GitHub = "https://github.com/francisafu"
    Email = "mail@francisfu.com"
    RSS = true 
  [params.page]
    [params.page.math]
      enable = true
      # mathematical formulas rendering engines, optional values: ["katex", "mathjax"]
      type = "katex"

      # KaTeX server-side rendering (https://katex.org)
      # KaTeX partial config: https://gohugo.io/functions/transform/tomath/#options
    [params.page.math.katex]
      # KaTeX extension copy-tex
      copyTex = true
      throwOnError = false
      errorColor = "#ff4949"

      # custom macros map
      # syntax: <macro> = <definition>
    [params.page.math.katex.macros]
      "\\f" = "#1f(#2)" # usage: $\f{a}{b}$

      # MathJax server-side rendering (https://www.mathjax.org)
      # MathJax config: https://docs.mathjax.org/en/latest/options/index.html
    [params.page.math.mathjax]
      cdn = "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"

    [params.page.math.mathjax.packages]
    # "[+]" = ['configmacros']

    # custom macros map
    # syntax: <macro> = <definition>
    [params.page.math.mathjax.macros]
    # "bold" = ["{\\bf #1}", 1] # usage: $\bold{math}$

    [params.page.math.mathjax.loader]
      load = [ "ui/safe" ]

    [params.page.math.mathjax.loader.paths]
    # custom = "https://cdn.jsdelivr.net/gh/sonoisa/XyJax-v3@3.0.1/build/"

    # more loader config e.g source, dependencies, provides etc.

    [params.page.math.mathjax.options]
      enableMenu = true
      # HTML tags that won't be searched for math
      skipHtmlTags = [
        "script",
        "noscript",
        "style",
        "textarea",
        "pre",
        "code",
        "math",
        "select",
        "option",
        "mjx-container"
      ]
      # class that marks tags not to search
      ignoreHtmlClass = "mathjax_ignore"
  
      # HTML tags that can appear within math
    [params.page.math.mathjax.options.includeHtmlTags]
    # "#comment" = ""
    # br = "\n"
    # wbr = ""
